baseURL = 'https://chaitanya.codes/'
languageCode = 'en-us'
title = 'Chaitanya.Codes'
theme = 'chaitanyacodes'
disqusShortname = 'bluedove-1'
rssLimit = 20
copyright = "2022 TheVasu All rights reserved"
googleAnalytics = ''
[params]
    description = ""
    author = "Chaitanya Chaturvedi"
	email = "chaitanya4vedi@gmail.com"
    authorImage = "/images/Chaitanya_Chaturvedi_Cropped.jpg"

paginate = 1

[[menu.main]]
  name = "Blog"
  url = "/blog"
   weight = 1

[[menu.main]]
    name = "Categories"
    url = "/categories"
     weight = 2

[[menu.main]]
    name = "Contact"
    url = "/contact"
     weight = 4

[[menu.main]]
  name = "About"
  url = "/about"
   weight = 3

[[menu.social]]
    name = "Facebook"
    url = "https:/facebook.com/chaitanya4vedi"
    pre = "<i class='fab fa-facebook'></i>"

[[menu.social]]
    name = "Twitter"
    url = "https://twitter.com/chaitanya4vedi"
    pre = "<i class='fab fa-twitter'></i>"

[[menu.social]]
    name = "Instagram"
    url = "https://instagram.com/chaitanya4vedi"
    pre = "<i class='fab fa-instagram'></i>"

[related]
    threshold = 0 
    includeNewer = true
    toLower = false

    [[related.indices]]
        name = "categories"
        weight = 100

    [[related.indices]]
        name = "date"
        weight = 10

[markup]
    [markup.goldmark]
        [markup.goldmark.renderer]
            unsafe = true

[[menu.footer]]
  name = "About"
  url = "/about"

[[menu.footer]]
  name = "Privacy"
  url = "/privacy"

[sitemap]
  changefreq = 'monthly'
  filename = 'sitemap.xml'
  priority = 0.5